"use strict";(self.webpackChunkpractica_docs=self.webpackChunkpractica_docs||[]).push([[9958],{5680:(e,t,n)=>{n.d(t,{xA:()=>u,yg:()=>g});var a=n(6540);function s(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function o(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function r(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?o(Object(n),!0).forEach((function(t){s(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):o(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function i(e,t){if(null==e)return{};var n,a,s=function(e,t){if(null==e)return{};var n,a,s={},o=Object.keys(e);for(a=0;a<o.length;a++)n=o[a],t.indexOf(n)>=0||(s[n]=e[n]);return s}(e,t);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(a=0;a<o.length;a++)n=o[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(s[n]=e[n])}return s}var l=a.createContext({}),c=function(e){var t=a.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):r(r({},t),e)),n},u=function(e){var t=c(e.components);return a.createElement(l.Provider,{value:t},e.children)},h="mdxType",d={inlineCode:"code",wrapper:function(e){var t=e.children;return a.createElement(a.Fragment,{},t)}},p=a.forwardRef((function(e,t){var n=e.components,s=e.mdxType,o=e.originalType,l=e.parentName,u=i(e,["components","mdxType","originalType","parentName"]),h=c(n),p=s,g=h["".concat(l,".").concat(p)]||h[p]||d[p]||o;return n?a.createElement(g,r(r({ref:t},u),{},{components:n})):a.createElement(g,r({ref:t},u))}));function g(e,t){var n=arguments,s=t&&t.mdxType;if("string"==typeof e||s){var o=n.length,r=new Array(o);r[0]=p;var i={};for(var l in t)hasOwnProperty.call(t,l)&&(i[l]=t[l]);i.originalType=e,i[h]="string"==typeof e?e:s,r[1]=i;for(var c=2;c<o;c++)r[c]=n[c];return a.createElement.apply(null,r)}return a.createElement.apply(null,n)}p.displayName="MDXCreateElement"},5881:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>l,contentTitle:()=>r,default:()=>d,frontMatter:()=>o,metadata:()=>i,toc:()=>c});var a=n(8168),s=(n(6540),n(5680));const o={slug:"testing-the-dark-scenarios-of-your-nodejs-application",date:"2023-07-07T11:00",hide_table_of_contents:!0,title:"Testing the dark scenarios of your Node.js application",authors:["goldbergyoni","razluvaton"],tags:["node.js","testing","component-test","fastify","unit-test","integration","nock"]},r=void 0,i={permalink:"/blog/testing-the-dark-scenarios-of-your-nodejs-application",editUrl:"https://github.com/practicajs/practica/tree/main/docs/blog/crucial-tests/index.md",source:"@site/blog/crucial-tests/index.md",title:"Testing the dark scenarios of your Node.js application",description:"Where the dead-bodies are covered",date:"2023-07-07T11:00:00.000Z",formattedDate:"July 7, 2023",tags:[{label:"node.js",permalink:"/blog/tags/node-js"},{label:"testing",permalink:"/blog/tags/testing"},{label:"component-test",permalink:"/blog/tags/component-test"},{label:"fastify",permalink:"/blog/tags/fastify"},{label:"unit-test",permalink:"/blog/tags/unit-test"},{label:"integration",permalink:"/blog/tags/integration"},{label:"nock",permalink:"/blog/tags/nock"}],readingTime:20.25,hasTruncateMarker:!1,authors:[{name:"Yoni Goldberg",title:"Practica.js core maintainer",url:"https://github.com/goldbergyoni",imageURL:"https://github.com/goldbergyoni.png",key:"goldbergyoni"},{name:"Raz Luvaton",title:"Practica.js core maintainer",url:"https://github.com/rluvaton",imageURL:"https://avatars.githubusercontent.com/u/16746759?v=4",key:"razluvaton"}],frontMatter:{slug:"testing-the-dark-scenarios-of-your-nodejs-application",date:"2023-07-07T11:00",hide_table_of_contents:!0,title:"Testing the dark scenarios of your Node.js application",authors:["goldbergyoni","razluvaton"],tags:["node.js","testing","component-test","fastify","unit-test","integration","nock"]},prevItem:{title:"A compilation of outstanding testing articles (with JavaScript)",permalink:"/blog/a-compilation-of-outstanding-testing-articles-with-javaScript"},nextItem:{title:"Practica v0.0.6 is alive",permalink:"/blog/practica-v0.0.6-is-alive"}},l={authorsImageUrls:[void 0,void 0]},c=[{value:"Where the dead-bodies are covered",id:"where-the-dead-bodies-are-covered",level:2},{value:"<strong>Test Examples</strong>",id:"test-examples",level:2},{value:"\ud83e\udddf\u200d\u2640\ufe0f The zombie process test",id:"\ufe0f-the-zombie-process-test",level:2},{value:"\ud83d\udc40 The observability test",id:"-the-observability-test",level:2},{value:"\ud83d\udc7d The &#39;unexpected visitor&#39; test - when an uncaught exception meets our code",id:"-the-unexpected-visitor-test---when-an-uncaught-exception-meets-our-code",level:2},{value:"\ud83d\udd75\ud83c\udffc The &#39;hidden effect&#39; test - when the code should not mutate at all",id:"-the-hidden-effect-test---when-the-code-should-not-mutate-at-all",level:2},{value:"\ud83e\udde8 The &#39;overdoing&#39; test - when the code should mutate but it&#39;s doing too much",id:"-the-overdoing-test---when-the-code-should-mutate-but-its-doing-too-much",level:2},{value:"\ud83d\udd70 The &#39;slow collaborator&#39; test - when the other HTTP service times out",id:"-the-slow-collaborator-test---when-the-other-http-service-times-out",level:2},{value:"\ud83d\udc8a The &#39;poisoned message&#39; test - when the message consumer gets an invalid payload that might put it in stagnation",id:"-the-poisoned-message-test---when-the-message-consumer-gets-an-invalid-payload-that-might-put-it-in-stagnation",level:2},{value:"\ud83d\udce6 Test the package as a consumer",id:"-test-the-package-as-a-consumer",level:2},{value:"\ud83d\uddde The &#39;broken contract&#39; test - when the code is great but its corresponding OpenAPI docs leads to a production bug",id:"-the-broken-contract-test---when-the-code-is-great-but-its-corresponding-openapi-docs-leads-to-a-production-bug",level:2},{value:"Even more ideas",id:"even-more-ideas",level:2},{value:"It&#39;s not just ideas, it a whole new mindset",id:"its-not-just-ideas-it-a-whole-new-mindset",level:2}],u={toc:c},h="wrapper";function d(e){let{components:t,...o}=e;return(0,s.yg)(h,(0,a.A)({},u,o,{components:t,mdxType:"MDXLayout"}),(0,s.yg)("h2",{id:"where-the-dead-bodies-are-covered"},"Where the dead-bodies are covered"),(0,s.yg)("p",null,"This post is about tests that are easy to write, 5-8 lines typically, they cover dark and dangerous corners of our applications, but are often overlooked"),(0,s.yg)("p",null,"Some context first: How do we test a modern backend? With ",(0,s.yg)("a",{parentName:"p",href:"https://ritesh-kapoor.medium.com/testing-automation-what-are-pyramids-and-diamonds-67494fec7c55"},"the testing diamond"),", of course, by putting the focus on component/integration tests that cover all the layers, including a real DB. With this approach, our tests 99% resemble the production and the user flows, while the development experience is almost as good as with unit tests. Sweet. If this topic is of interest, we've also written ",(0,s.yg)("a",{parentName:"p",href:"https://github.com/testjavascript/nodejs-integration-tests-best-practices"},"a guide with 50 best practices for integration tests in Node.js")),(0,s.yg)("p",null,"But there is a pitfall: most developers write ",(0,s.yg)("em",{parentName:"p"},"only")," semi-happy test cases that are focused on the core user flows. Like invalid inputs, CRUD operations, various application states, etc. This is indeed the bread and butter, a great start, but a whole area is left uncovered. For example, typical tests don't simulate an unhandled promise rejection that leads to process crash, nor do they simulate the webserver bootstrap phase that might fail and leave the process idle, or HTTP calls to external services that often end with timeouts and retries. They typically not covering the health and readiness route, nor the integrity of the OpenAPI to the actual routes schema, to name just a few examples. There are many dead bodies covered beyond business logic, things that sometimes are even beyond bugs but rather are concerned with application downtime"),(0,s.yg)("p",null,(0,s.yg)("img",{alt:"The hidden corners",src:n(3132).A,width:"900",height:"521"})),(0,s.yg)("p",null,"Here are a handful of examples that might open your mind to a whole new class of risks and tests"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"July 2023: My testing course was launched: I've just released a comprehensive testing course that I've been working on for two years. \ud83c\udf81 It's now on sale, but only for the month of July. Check it out at ",(0,s.yg)("a",{parentName:"strong",href:"https://testjavascript.com/"},"testjavascript.com"))),(0,s.yg)("h2",{id:"test-examples"},(0,s.yg)("strong",{parentName:"h2"},"Test Examples")),(0,s.yg)("h2",{id:"\ufe0f-the-zombie-process-test"},"\ud83e\udddf\u200d\u2640\ufe0f The zombie process test"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udc49What & so what? -")," In all of your tests, you assume that the app has already started successfully, lacking a test against the initialization flow. This is a pity because this phase hides some potential catastrophic failures: First, initialization failures are frequent - many bad things can happen here, like a DB connection failure or a new version that crashes during deployment. For this reason, runtime platforms (like Kubernetes and others) encourage components to signal when they are ready (see ",(0,s.yg)("a",{parentName:"p",href:"https://komodor.com/learn/kubernetes-readiness-probes-a-practical-guide/#:~:text=A%20readiness%20probe%20allows%20Kubernetes,on%20deletion%20of%20a%20pod."},"readiness probe"),"). Errors at this stage also have a dramatic effect over the app health - if the initialization fails and the process stays alive, it becomes a 'zombie process'. In this scenario, the runtime platform won't realize that something went bad, forward traffic to it and avoid creating alternative instances. Besides exiting gracefully, you may want to consider logging, firing a metric, and adjusting your /readiness route. Does it work? only test can tell!"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udcdd Code")),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"Code under test, api.js:")),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-javascript"},"// A common express server initialization\nconst startWebServer = () => {\n  return new Promise((resolve, reject) => {\n    try {\n      // A typical Express setup\n      expressApp = express();\n      defineRoutes(expressApp); // a function that defines all routes\n      expressApp.listen(process.env.WEB_SERVER_PORT);\n    } catch (error) {\n      //log here, fire a metric, maybe even retry and finally:\n      process.exit();\n    }\n  });\n};\n")),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"The test:")),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-javascript"},"const api = require('./entry-points/api'); // our api starter that exposes 'startWebServer' function\nconst sinon = require('sinon'); // a mocking library\n\ntest('When an error happens during the startup phase, then the process exits', async () => {\n  // Arrange\n  const processExitListener = sinon.stub(process, 'exit');\n  // \ud83d\udc47 Choose a function that is part of the initialization phase and make it fail\n  sinon\n    .stub(routes, 'defineRoutes')\n    .throws(new Error('Cant initialize connection'));\n\n  // Act\n  await api.startWebServer();\n\n  // Assert\n  expect(processExitListener.called).toBe(true);\n});\n")),(0,s.yg)("h2",{id:"-the-observability-test"},"\ud83d\udc40 The observability test"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udc49What & why -")," For many, testing error means checking the exception type or the API response. This leaves one of the most essential parts uncovered - making the error ",(0,s.yg)("strong",{parentName:"p"},"correctly observable"),". In plain words, ensuring that it's being logged correctly and exposed to the monitoring system. It might sound like an internal thing, implementation testing, but actually, it goes directly to a user. Yes, not the end-user, but rather another important one - the ops user who is on-call. What are the expectations of this user? At the very basic level, when a production issue arises, she must see detailed log entries, ",(0,s.yg)("em",{parentName:"p"},"including stack trace"),", cause and other properties. This info can save the day when dealing with production incidents. On to of this, in many systems, monitoring is managed separately to conclude about the overall system state using cumulative heuristics (e.g., an increase in the number of errors over the last 3 hours). To support this monitoring needs, the code also must fire error metrics. Even tests that do try to cover these needs take a naive approach by checking that the logger function was called - but hey, does it include the right data? Some write better tests that check the error type that was passed to the logger, good enough? No! The ops user doesn't care about the JavaScript class names but the JSON data that is sent out. The following test focuses on the specific properties that are being made observable:"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udcdd Code")),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-javascript"},"test('When exception is throw during request, Then logger reports the mandatory fields', async () => {\n  //Arrange\n  const orderToAdd = {\n    userId: 1,\n    productId: 2,\n    status: 'approved',\n  };\n  const metricsExporterDouble = sinon.stub(metricsExporter, 'fireMetric');\n  sinon\n    .stub(OrderRepository.prototype, 'addOrder')\n    .rejects(new AppError('saving-failed', 'Order could not be saved', 500));\n  const loggerDouble = sinon.stub(logger, 'error');\n\n  //Act\n  await axiosAPIClient.post('/order', orderToAdd);\n\n  //Assert\n  expect(loggerDouble).toHaveBeenCalledWith({\n    name: 'saving-failed',\n    status: 500,\n    stack: expect.any(String),\n    message: expect.any(String),\n  });\n  expect(\n    metricsExporterDouble).toHaveBeenCalledWith('error', {\n      errorName: 'example-error',\n    })\n});\n")),(0,s.yg)("h2",{id:"-the-unexpected-visitor-test---when-an-uncaught-exception-meets-our-code"},"\ud83d\udc7d The 'unexpected visitor' test - when an uncaught exception meets our code"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udc49What & why -")," A typical error flow test falsely assumes two conditions: A valid error object was thrown, and it was caught. Neither is guaranteed, let's focus on the 2nd assumption: it's common for certain errors to left uncaught. The error might get thrown before your framework error handler is ready, some npm libraries can throw surprisingly from different stacks using timer functions, or you just forget to set someEventEmitter.on('error', ...). To name a few examples. These errors will find their way to the global process.on('uncaughtException') handler, ",(0,s.yg)("strong",{parentName:"p"},"hopefully if your code subscribed"),". How do you simulate this scenario in a test? naively you may locate a code area that is not wrapped with try-catch and stub it to throw during the test. But here's a catch22: if you are familiar with such area - you are likely to fix it and ensure its errors are caught. What do we do then? we can bring to our benefit the fact the JavaScript is 'borderless', if some object can emit an event, we as its subscribers can make it emit this event ourselves, here's an example:"),(0,s.yg)("p",null,"researches says that, rejection"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udcdd Code")),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-javascript"},"test('When an unhandled exception is thrown, then process stays alive and the error is logged', async () => {\n  //Arrange\n  const loggerDouble = sinon.stub(logger, 'error');\n  const processExitListener = sinon.stub(process, 'exit');\n  const errorToThrow = new Error('An error that wont be caught \ud83d\ude33');\n\n  //Act\n  process.emit('uncaughtException', errorToThrow); //\ud83d\udc48 Where the magic is\n\n  // Assert\n  expect(processExitListener.called).toBe(false);\n  expect(loggerDouble).toHaveBeenCalledWith(errorToThrow);\n});\n")),(0,s.yg)("h2",{id:"-the-hidden-effect-test---when-the-code-should-not-mutate-at-all"},"\ud83d\udd75\ud83c\udffc The 'hidden effect' test - when the code should not mutate at all"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udc49What & so what -")," In common scenarios, the code under test should stop early like when the incoming payload is invalid or a user doesn't have sufficient credits to perform an operation. In these cases, no DB records should be mutated. Most tests out there in the wild settle with testing the HTTP response only - got back HTTP 400? great, the validation/authorization probably work. Or does it? The test trusts the code too much, a valid response doesn't guarantee that the code behind behaved as design. Maybe a new record was added although the user has no permissions? Clearly you need to test this, but how would you test that a record was NOT added? There are two options here: If the DB is purged before/after every test, than just try to perform an invalid operation and check that the DB is empty afterward. If you're not cleaning the DB often (like me, but that's another discussion), the payload must contain some unique and queryable value that you can query later and hope to get no records. This is how it looks like:"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udcdd Code")),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-javascript"},"it('When adding an invalid order, then it returns 400 and NOT retrievable', async () => {\n  //Arrange\n  const orderToAdd = {\n    userId: 1,\n    mode: 'draft',\n    externalIdentifier: uuid(), //no existing record has this value\n  };\n\n  //Act\n  const { status: addingHTTPStatus } = await axiosAPIClient.post(\n    '/order',\n    orderToAdd\n  );\n\n  //Assert\n  const { status: fetchingHTTPStatus } = await axiosAPIClient.get(\n    `/order/externalIdentifier/${orderToAdd.externalIdentifier}`\n  ); // Trying to get the order that should have failed\n  expect({ addingHTTPStatus, fetchingHTTPStatus }).toMatchObject({\n    addingHTTPStatus: 400,\n    fetchingHTTPStatus: 404,\n  });\n  // \ud83d\udc46 Check that no such record exists\n});\n")),(0,s.yg)("h2",{id:"-the-overdoing-test---when-the-code-should-mutate-but-its-doing-too-much"},"\ud83e\udde8 The 'overdoing' test - when the code should mutate but it's doing too much"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udc49What & why -")," This is how a typical data-oriented test looks like: first you add some records, then approach the code under test, and finally assert what happens to these specific records. So far, so good. There is one caveat here though: since the test narrows it focus to specific records, it ignores whether other record were unnecessarily affected. This can be really bad, here's a short real-life story that happened to my customer: Some data access code changed and incorporated a bug that updates ALL the system users instead of just one. All test pass since they focused on a specific record which positively updated, they just ignored the others. How would you test and prevent? here is a nice trick that I was taught by my friend Gil Tayar: in the first phase of the test, besides the main records, add one or more 'control' records that should not get mutated during the test. Then, run the code under test, and besides the main assertion, check also that the control records were not affected:"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udcdd Code")),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-javascript"},"test('When deleting an existing order, Then it should NOT be retrievable', async () => {\n  // Arrange\n  const orderToDelete = {\n    userId: 1,\n    productId: 2,\n  };\n  const deletedOrder = (await axiosAPIClient.post('/order', orderToDelete)).data\n    .id; // We will delete this soon\n  const orderNotToBeDeleted = orderToDelete;\n  const notDeletedOrder = (\n    await axiosAPIClient.post('/order', orderNotToBeDeleted)\n  ).data.id; // We will not delete this\n\n  // Act\n  await axiosAPIClient.delete(`/order/${deletedOrder}`);\n\n  // Assert\n  const { status: getDeletedOrderStatus } = await axiosAPIClient.get(\n    `/order/${deletedOrder}`\n  );\n  const { status: getNotDeletedOrderStatus } = await axiosAPIClient.get(\n    `/order/${notDeletedOrder}`\n  );\n  expect(getNotDeletedOrderStatus).toBe(200);\n  expect(getDeletedOrderStatus).toBe(404);\n});\n")),(0,s.yg)("h2",{id:"-the-slow-collaborator-test---when-the-other-http-service-times-out"},"\ud83d\udd70 The 'slow collaborator' test - when the other HTTP service times out"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udc49What & why -")," When your code approaches other services/microservices via HTTP, savvy testers minimize end-to-end tests because these tests lean toward happy paths (it's harder to simulate scenarios). This mandates using some mocking tool to act like the remote service, for example, using tools like ",(0,s.yg)("a",{parentName:"p",href:"https://github.com/nock/nock"},"nock")," or ",(0,s.yg)("a",{parentName:"p",href:"https://wiremock.org/"},"wiremock"),". These tools are great, only some are using them naively and check mainly that calls outside were indeed made. What if the other service is not available ",(0,s.yg)("strong",{parentName:"p"},"in production"),", what if it is slower and times out occasionally (one of the biggest risks of Microservices)? While you can't wholly save this transaction, your code should do the best given the situation and retry, or at least log and return the right status to the caller. All the network mocking tools allow simulating delays, timeouts and other 'chaotic' scenarios. Question left is how to simulate slow response without having slow tests? You may use ",(0,s.yg)("a",{parentName:"p",href:"https://sinonjs.org/releases/latest/fake-timers/"},"fake timers")," and trick the system into believing as few seconds passed in a single tick. If you're using ",(0,s.yg)("a",{parentName:"p",href:"https://github.com/nock/nock"},"nock"),", it offers an interesting feature to simulate timeouts ",(0,s.yg)("strong",{parentName:"p"},"quickly"),": the .delay function simulates slow responses, then nock will realize immediately if the delay is higher than the HTTP client timeout and throw a timeout event immediately without waiting"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udcdd Code")),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-javascript"},"// In this example, our code accepts new Orders and while processing them approaches the Users Microservice\ntest('When users service times out, then return 503 (option 1 with fake timers)', async () => {\n  //Arrange\n  const clock = sinon.useFakeTimers();\n  config.HTTPCallTimeout = 1000; // Set a timeout for outgoing HTTP calls\n  nock(`${config.userServiceURL}/user/`)\n    .get('/1', () => clock.tick(2000)) // Reply delay is bigger than configured timeout \ud83d\udc46\n    .reply(200);\n  const loggerDouble = sinon.stub(logger, 'error');\n  const orderToAdd = {\n    userId: 1,\n    productId: 2,\n    mode: 'approved',\n  };\n\n  //Act\n  // \ud83d\udc47try to add new order which should fail due to User service not available\n  const response = await axiosAPIClient.post('/order', orderToAdd);\n\n  //Assert\n  // \ud83d\udc47At least our code does its best given this situation\n  expect(response.status).toBe(503);\n  expect(loggerDouble.lastCall.firstArg).toMatchObject({\n    name: 'user-service-not-available',\n    stack: expect.any(String),\n    message: expect.any(String),\n  });\n});\n")),(0,s.yg)("h2",{id:"-the-poisoned-message-test---when-the-message-consumer-gets-an-invalid-payload-that-might-put-it-in-stagnation"},"\ud83d\udc8a The 'poisoned message' test - when the message consumer gets an invalid payload that might put it in stagnation"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udc49What & so what -")," When testing flows that start or end in a queue, I bet you're going to bypass the message queue layer, where the code and libraries consume a queue, and you approach the logic layer directly. Yes, it makes things easier but leaves a class of uncovered risks. For example, what if the logic part throws an error or the message schema is invalid but the message queue consumer fails to translate this exception into a proper message queue action? For example, the consumer code might fail to reject the message or increment the number of attempts (depends on the type of queue that you're using). When this happens, the message will enter a loop where it always served again and again. Since this will apply to many messages, things can get really bad as the queue gets highly saturated. For this reason this syndrome was called the 'poisoned message'. To mitigate this risk, the tests' scope must include all the layers like how you probably do when testing against APIs. Unfortunately, this is not as easy as testing with DB because message queues are flaky, here is why"),(0,s.yg)("p",null,"When testing with real queues things get curios and curiouser: tests from different process will steal messages from each other, purging queues is harder that you might think (e.g. ",(0,s.yg)("a",{parentName:"p",href:"https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-using-purge-queue.html"},"SQS demand 60 seconds")," to purge queues), to name a few challenges that you won't find when dealing with real DB"),(0,s.yg)("p",null,"Here is a strategy that works for many teams and holds a small compromise - use a fake in-memory message queue. By 'fake' I mean something simplistic that acts like a stub/spy and do nothing but telling when certain calls are made (e.g., consume, delete, publish). You might find reputable fakes/stubs for your own message queue like ",(0,s.yg)("a",{parentName:"p",href:"https://github.com/m-radzikowski/aws-sdk-client-mock"},"this one for SQS")," and you can code one ",(0,s.yg)("strong",{parentName:"p"},"easily")," yourself. No worries, I'm not a favour of maintaining myself testing infrastructure, this proposed component is extremely simply and unlikely to surpass 50 lines of code (see example below). On top of this, whether using a real or fake queue, one more thing is needed: create a convenient interface that tells to the test when certain things happened like when a message was acknowledged/deleted or a new message was published. Without this, the test never knows when certain events happened and lean toward quirky techniques like polling. Having this setup, the test will be short, flat and you can easily simulate common message queue scenarios like out of order messages, batch reject, duplicated messages and in our example - the poisoned message scenario (using RabbitMQ):"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udcdd Code")),(0,s.yg)("ol",null,(0,s.yg)("li",{parentName:"ol"},"Create a fake message queue that does almost nothing but record calls, see full example here")),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-javascript"},"class FakeMessageQueueProvider extends EventEmitter {\n  // Implement here\n\n  publish(message) {}\n\n  consume(queueName, callback) {}\n}\n")),(0,s.yg)("ol",{start:2},(0,s.yg)("li",{parentName:"ol"},"Make your message queue client accept real or fake provider")),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-javascript"},"class MessageQueueClient extends EventEmitter {\n  // Pass to it a fake or real message queue\n  constructor(customMessageQueueProvider) {}\n\n  publish(message) {}\n\n  consume(queueName, callback) {}\n\n  // Simple implementation can be found here:\n  // https://github.com/testjavascript/nodejs-integration-tests-best-practices/blob/master/example-application/libraries/fake-message-queue-provider.js\n}\n")),(0,s.yg)("ol",{start:3},(0,s.yg)("li",{parentName:"ol"},"Expose a convenient function that tells when certain calls where made")),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-javascript"},"class MessageQueueClient extends EventEmitter {\n  publish(message) {}\n\n  consume(queueName, callback) {}\n\n  // \ud83d\udc47\n  waitForEvent(eventName: 'publish' | 'consume' | 'acknowledge' | 'reject', howManyTimes: number) : Promise\n}\n")),(0,s.yg)("ol",{start:4},(0,s.yg)("li",{parentName:"ol"},"The test is now short, flat and expressive \ud83d\udc47")),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-javascript"},"const FakeMessageQueueProvider = require('./libs/fake-message-queue-provider');\nconst MessageQueueClient = require('./libs/message-queue-client');\nconst newOrderService = require('./domain/newOrderService');\n\ntest('When a poisoned message arrives, then it is being rejected back', async () => {\n  // Arrange\n  const messageWithInvalidSchema = { nonExistingProperty: 'invalid\u274c' };\n  const messageQueueClient = new MessageQueueClient(\n    new FakeMessageQueueProvider()\n  );\n  // Subscribe to new messages and passing the handler function\n  messageQueueClient.consume('orders.new', newOrderService.addOrder);\n\n  // Act\n  await messageQueueClient.publish('orders.new', messageWithInvalidSchema);\n  // Now all the layers of the app will get stretched \ud83d\udc46, including logic and message queue libraries\n\n  // Assert\n  await messageQueueClient.waitFor('reject', { howManyTimes: 1 });\n  // \ud83d\udc46 This tells us that eventually our code asked the message queue client to reject this poisoned message\n});\n")),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udcddFull code example -")," ",(0,s.yg)("a",{parentName:"p",href:"https://github.com/testjavascript/nodejs-integration-tests-best-practices/blob/master/recipes/message-queue/fake-message-queue.test.js"},"is here")),(0,s.yg)("h2",{id:"-test-the-package-as-a-consumer"},"\ud83d\udce6 Test the package as a consumer"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udc49What & why -")," When publishing a library to npm, easily all your tests might pass BUT... the same functionality will fail over the end-user's computer. How come? tests are executed against the local developer files, but the end-user is only exposed to artifacts ",(0,s.yg)("em",{parentName:"p"},"that were built"),". See the mismatch here? ",(0,s.yg)("em",{parentName:"p"},"after")," running the tests, the package files are transpiled (I'm looking at you babel users), zipped and packed. If a single file is excluded due to .npmignore or a polyfill is not added correctly, the published code will lack mandatory files"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udcdd Code")),(0,s.yg)("p",null,"Consider the following scenario, you're developing a library, and you wrote this code:"),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-js"},"// index.js\nexport * from './calculate.js';\n\n// calculate.js \ud83d\udc48\nexport function calculate() {\n  return 1;\n}\n")),(0,s.yg)("p",null,"Then some tests:"),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-js"},"import { calculate } from './index.js';\n\ntest('should return 1', () => {\n  expect(calculate()).toBe(1);\n})\n\n\u2705 All tests pass \ud83c\udf8a\n")),(0,s.yg)("p",null,"Finally configure the package.json:"),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-json5"},'{\n  // ....\n  "files": [\n    "index.js"\n  ]\n}\n')),(0,s.yg)("p",null,"See, 100% coverage, all tests pass locally and in the CI \u2705, it just won't work in production \ud83d\udc79. Why? because you forgot to include the ",(0,s.yg)("inlineCode",{parentName:"p"},"calculate.js")," in the package.json ",(0,s.yg)("inlineCode",{parentName:"p"},"files")," array \ud83d\udc46"),(0,s.yg)("p",null,"What can we do instead? we can test the library as ",(0,s.yg)("em",{parentName:"p"},"its end-users"),". How? publish the package to a local registry like ",(0,s.yg)("a",{parentName:"p",href:"https://verdaccio.org/"},"verdaccio"),", let the tests install and approach the ",(0,s.yg)("em",{parentName:"p"},"published")," code. Sounds troublesome? judge yourself \ud83d\udc47"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udcdd Code")),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-js"},"// global-setup.js\n\n// 1. Setup the in-memory NPM registry, one function that's it! \ud83d\udd25\nawait setupVerdaccio();\n\n// 2. Building our package \nawait exec('npm', ['run', 'build'], {\n    cwd: packagePath,\n});\n\n// 3. Publish it to the in-memory registry\nawait exec('npm', ['publish', '--registry=http://localhost:4873'], {\n    cwd: packagePath,\n});\n\n// 4. Installing it in the consumer directory\nawait exec('npm', ['install', 'my-package', '--registry=http://localhost:4873'], {\n    cwd: consumerPath,\n});\n\n// Test file in the consumerPath\n\n// 5. Test the package \ud83d\ude80\ntest(\"should succeed\", async () => {\n    const { fn1 } = await import('my-package');\n\n    expect(fn1()).toEqual(1);\n});\n")),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udcddFull code example -")," ",(0,s.yg)("a",{parentName:"p",href:"https://github.com/rluvaton/e2e-verdaccio-example"},"is here")),(0,s.yg)("p",null,"What else this technique can be useful for?"),(0,s.yg)("ul",null,(0,s.yg)("li",{parentName:"ul"},"Testing different version of peer dependency you support - let's say your package support react 16 to 18, you can now test that"),(0,s.yg)("li",{parentName:"ul"},"You want to test ESM and CJS consumers"),(0,s.yg)("li",{parentName:"ul"},"If you have CLI application you can test it like your users"),(0,s.yg)("li",{parentName:"ul"},"Making sure all the voodoo magic in that babel file is working as expected")),(0,s.yg)("h2",{id:"-the-broken-contract-test---when-the-code-is-great-but-its-corresponding-openapi-docs-leads-to-a-production-bug"},"\ud83d\uddde The 'broken contract' test - when the code is great but its corresponding OpenAPI docs leads to a production bug"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udc49What & so what -"),' Quite confidently I\'m sure that almost no team test their OpenAPI correctness. "It\'s just documentation", "we generate it automatically based on code" are typical belief found for this reason. Let me show you how this auto generated documentation can be wrong and lead not only to frustration but also to a bug. In production.'),(0,s.yg)("p",null,"Consider the following scenario, you're requested to return HTTP error status code if an order is duplicated but forget to update the OpenAPI specification with this new HTTP status response. While some framework can update the docs with new fields, none can realize which errors your code throws, this labour is always manual. On the other side of the line, the API client is doing everything just right, going by the spec that you published, adding orders with some duplication because the docs don't forbid doing so. Then, BOOM, production bug -> the client crashes and shows an ugly unknown error message to the user. This type of failure is called the 'contract' problem when two parties interact, each has a code that works perfect, they just operate under different spec and assumptions. While there are fancy sophisticated and exhaustive solution to this challenge (e.g., ",(0,s.yg)("a",{parentName:"p",href:"https://pact.io"},"PACT"),"), there are also leaner approaches that gets you covered ",(0,s.yg)("em",{parentName:"p"},"easily and quickly")," (at the price of covering less risks)."),(0,s.yg)("p",null,"The following sweet technique is based on libraries (jest, mocha) that listen to all network responses, compare the payload against the OpenAPI document, and if any deviation is found - make the test fail with a descriptive error. With this new weapon in your toolbox and almost zero effort, another risk is ticked. It's a pity that these libs can't assert also against the incoming requests to tell you that your tests use the API wrong. One small caveat and an elegant solution: These libraries dictate putting an assertion statement in every test - expect(response).toSatisfyApiSpec(), a bit tedious and relies on human discipline. You can do better if your HTTP client supports plugin/hook/interceptor by putting this assertion in a single place that will apply in all the tests:"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"\ud83d\udcdd Code")),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"Code under test, an API throw a new error status")),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-javascript"},"if (doesOrderCouponAlreadyExist) {\n  throw new AppError('duplicated-coupon', { httpStatus: 409 });\n}\n")),(0,s.yg)("p",null,"The OpenAPI doesn't document HTTP status '409', no framework knows to update the OpenAPI doc based on thrown exceptions"),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-json"},'"responses": {\n    "200": {\n      "description": "successful",\n      }\n    ,\n    "400": {\n      "description": "Invalid ID",\n      "content": {}\n    },// No 409 in this list\ud83d\ude32\ud83d\udc48\n}\n\n')),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"The test code")),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-javascript"},"const jestOpenAPI = require('jest-openapi');\njestOpenAPI('../openapi.json');\n\ntest('When an order with duplicated coupon is added , then 409 error should get returned', async () => {\n  // Arrange\n  const orderToAdd = {\n    userId: 1,\n    productId: 2,\n    couponId: uuid(),\n  };\n  await axiosAPIClient.post('/order', orderToAdd);\n\n  // Act\n  // We're adding the same coupon twice \ud83d\udc47\n  const receivedResponse = await axios.post('/order', orderToAdd);\n\n  // Assert;\n  expect(receivedResponse.status).toBe(409);\n  expect(res).toSatisfyApiSpec();\n  // This \ud83d\udc46 will throw if the API response, body or status, is different that was it stated in the OpenAPI\n});\n")),(0,s.yg)("p",null,"Trick: If your HTTP client supports any kind of plugin/hook/interceptor, put the following code in 'beforeAll'. This covers all the tests against OpenAPI mismatches"),(0,s.yg)("pre",null,(0,s.yg)("code",{parentName:"pre",className:"language-javascript"},"beforeAll(() => {\n  axios.interceptors.response.use((response) => {\n    expect(response.toSatisfyApiSpec());\n    // With this \ud83d\udc46, add nothing to the tests - each will fail if the response deviates from the docs\n  });\n});\n")),(0,s.yg)("h2",{id:"even-more-ideas"},"Even more ideas"),(0,s.yg)("ul",null,(0,s.yg)("li",{parentName:"ul"},"Test readiness and health routes"),(0,s.yg)("li",{parentName:"ul"},"Test message queue connection failures"),(0,s.yg)("li",{parentName:"ul"},"Test JWT and JWKS failures"),(0,s.yg)("li",{parentName:"ul"},"Test security-related things like CSRF tokens"),(0,s.yg)("li",{parentName:"ul"},"Test your HTTP client retry mechanism (very easy with nock)"),(0,s.yg)("li",{parentName:"ul"},"Test that the DB migration succeed and the new code can work with old records format"),(0,s.yg)("li",{parentName:"ul"},"Test DB connection disconnects")),(0,s.yg)("h2",{id:"its-not-just-ideas-it-a-whole-new-mindset"},"It's not just ideas, it a whole new mindset"),(0,s.yg)("p",null,"The examples above were not meant only to be a checklist of 'don't forget' test cases, but rather a fresh mindset on what tests could cover for you. Modern tests are not just about functions, or user flows, but any risk that might visit your production. This is doable only with component/integration tests but never with unit or end-to-end tests. Why? Because unlike unit you need all the parts to play together (e.g., the DB migration file, with the DAL layer and the error handler all together). Unlike E2E, you have the power to simulate in-process scenarios that demand some tweaking and mocking. Component tests allow you to include many production moving parts early on your machine. I like calling this 'production-oriented development'"),(0,s.yg)("p",null,(0,s.yg)("strong",{parentName:"p"},"My new online testing course -")," If you're intrigued with beyond the basics testing patterns, ",(0,s.yg)("a",{parentName:"p",href:"https://testjavascript.com"},"consider my online course which was just launched and is \ud83c\udf81 on sale for 30 days (July 2023)")))}d.isMDXComponent=!0},3132:(e,t,n)=>{n.d(t,{A:()=>a});const a=n.p+"assets/images/the-hidden-corners-44855c2e5d9184502e1dc72b07d53cef.png"}}]);